x-common: &common
  env_file:
    - .env
  networks:
    - demas-network

services:
  redis:
    container_name: demas-redis
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  django:
    <<: *common
    container_name: demas-django
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    command: uv run manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: dockerfile
      target: django-runner
    working_dir: /app/src
    volumes:
      - .:/app/

  celery-worker:
    <<: *common
    container_name: celery-worker
    working_dir: /app/src
    build:
      context: .
      dockerfile: dockerfile
      target: django-runner
    depends_on:
      redis:
        condition: service_healthy
      django:
        condition: service_started
    volumes:
      - .:/app/
    command: uv run celery -A main.celery worker --loglevel=info --concurrency=5
    restart: unless-stopped

  frontend:
    <<: *common
    container_name: demas-frontend
    build:
      context: .
      dockerfile: dockerfile
      target: frontend-runner
    working_dir: /app/frontend
    command: pnpm start --port 3000
    ports:
      - "3000:3000"


volumes:
  redis_data:
  app_data:

networks:
  demas-network:
    driver: bridge
